spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  application:
    name: API-MARK
  datasource:
    url: jdbc:postgresql://localhost:5432/mark
    driveClassName: org.postgresql.Driver
    username: admin
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: filesystem:flyway/db
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create-drop

is:
  keycloak:
    admin:
      user: admin
      password: admin
# Keycloak settings
keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://localhost:8080/auth/
  ssl-required: none
  resource: is-keycloak
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username
server:
  port: 8085

